# Generated by Django 4.2.4 on 2023-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CourtMaster", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="name",
            new_name="case_date",
        ),
        migrations.RemoveField(
            model_name="case",
            name="created",
        ),
        migrations.AddField(
            model_name="case",
            name="case_info",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="case_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="case_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="case_time",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="case_type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
